services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8090:8080"
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - dev

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    ports:
      - "3306"
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --protocol tcp
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

volumes:
  mysqldb: