spring:
  datasource:
    url: jdbc:h2:mem:test
  docker:
    compose:
      enabled: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      data-locations: classpath:testdata.sql
