name: jchat

services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=tajneHaslo"
      - "MYSQL_DATABASE=jchat"
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --protocol tcp
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

  application:
    build: .
    image: javastart/jchat
    pull_policy: build
    container_name: jchat
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: wget --spider localhost:8080
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

volumes:
  mysqldb:
