name: jchat

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    environment:
      - "MYSQL_ROOT_PASSWORD=tajneHaslo"
      - "MYSQL_DATABASE=jchat"
    volumes:
      - jchat-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --protocol tcp
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

  application:
    container_name: jchat
    build: .
    image: javastart/jchat:1.0
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  jchat-volume:
