name: jchat

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    environment:
      - "MYSQL_ROOT_PASSWORD=tajneHaslo"
      - "MYSQL_DATABASE=jchat"
    volumes:
      - jchat-volume:/var/lib/mysql

  application:
    container_name: jchat
    build: .
    ports:
      - "8080:8080"

volumes:
  jchat-volume: