spring:
  docker:
    compose:
      file: compose-database.yml
      profiles:
        active: dev
      stop:
        command: down
      skip:
        in-tests: false
  sql:
    init:
      data-locations: classpath:testdata.sql